[platformio]
extra_configs = secrets.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D DEFAULT_WIFI_SSID=\"${secrets.wifi_ssid}\"
    -D DEFAULT_WIFI_PASS=\"${secrets.wifi_pass}\"
    -D MQTT_BROKER_HOST=\"${secrets.mqtt_host}\"
    -D MQTT_BROKER_PORT=${secrets.mqtt_port}
    -D MQTT_USER=\"${secrets.mqtt_user}\"
    -D MQTT_PASS=\"${secrets.mqtt_pass}\"
    -D MQTT_TOPIC_BASE=\"${secrets.mqtt_topic_base}\"
    -D SENSOR_READ_INTERVAL_MS=${secrets.sensor_read_interval_ms}
    -D HEALTH_CHECK_INTERVAL_MS=${secrets.health_check_interval_ms}

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.4
    https://github.com/tzapu/WiFiManager.git#v2.0.17
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit Unified Sensor@^1.1.14
